services:
  database:
    image: postgres:15
    container_name: db_data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5433"  # O PostgreSQL usa a porta 5432 internamente
    volumes:
      - db_data:/var/lib/postgresql/data  # Mapeamento correto do volume para o diretório do PostgreSQL

volumes:
  db_data: